apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: spine
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: spine
  name: read-secrets
subjects:
- kind: ServiceAccount
  name: olaf
  namespace: spine
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
