apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  namespace: spine
spec:
  replicas: 4
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik-container
        image: traefik:v2.5
        args:
        - --api.insecure=true
        - --providers.kubernetesingress=true
